/**
 * Every user-visible string of the training module.
 *
 * The rest of the panel is written in Spanish; the training module is written in English on
 * purpose (plan §14, decision 4) because the whole panel gets translated in the launch plan and
 * writing it in Spanish today would be double work. Centralising the strings here is what makes
 * that translation a single pull request instead of a hunt through twenty files.
 *
 * Tone (UX spec §9): one line, verb first, no exclamation marks, no emoji, no blame. A missed
 * session is a fact ("3 sessions missed this block"), never a reproach.
 */

export const trainingStrings = {
  // ---------------------------------------------------------------- navigation
  nav: {
    training: 'Training',
    programs: 'Programs',
    exercises: 'Exercises',
  },

  // ---------------------------------------------------------------- shared
  common: {
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    duplicate: 'Duplicate',
    create: 'Create',
    retry: 'Retry',
    back: 'Back',
    search: 'Search',
    loading: 'Loading…',
    dismiss: 'Dismiss',
    week: 'Week',
    weeks: 'weeks',
    day: 'Day',
    days: 'days',
    exercises: 'exercises',
    optional: 'optional',
    none: '—',
    genericError: 'Something went wrong. Try again.',
    loadError: 'Could not load this page.',
    saveError: "Couldn't save. Your changes are still here.",
    // A 403 from the module gate is not a failure: nothing broke, the module is switched off.
    // Offering "Retry" there would be a lie, so this state has a way forward instead.
    moduleInactive: "The Training module isn't active in this workspace.",
    moduleInactiveAction: 'Turn it on in Features',
  },

  // ---------------------------------------------------------------- /training
  programs: {
    title: 'Programs',
    subtitle: 'Write a program once, assign it to a client or a group.',
    newProgram: 'New program',
    createTitle: 'New program',
    name: 'Name',
    namePlaceholder: 'Off-season strength',
    description: 'Description',
    goal: 'Goal',
    goalPlaceholder: 'Strength',
    durationWeeks: 'Duration in weeks',
    visibility: 'Visibility',
    visibilityPrivate: 'Private',
    visibilityGroup: 'Group',
    visibilityHint: 'Group programs show who trained today. Private programs show nothing social.',
    statusDraft: 'Draft',
    statusActive: 'Active',
    statusArchived: 'Archived',
    assignedCount: (n: number) => (n === 1 ? '1 client assigned' : `${n} clients assigned`),
    weeksCount: (n: number) => (n === 1 ? '1 week' : `${n} weeks`),
    search: 'Search programs',
    filterAll: 'All',
    empty: 'No programs yet.',
    emptyAction: 'Create your first program',
    emptyFiltered: 'No programs match this filter.',
    loadError: "Couldn't load programs.",
    createError: "Couldn't create the program.",
    nameRequired: 'Name is required.',
    durationRange: 'Duration must be between 1 and 52 weeks.',
    created: 'Program created',
    duplicated: 'Program duplicated',
    deleted: 'Program deleted',
    confirmDelete: 'Delete this program? Programs with active assignments cannot be deleted.',
    deleteBlockedByAssignments: 'This program has active assignments. Archive it instead.',
  },

  // ---------------------------------------------------- /training/programs/[id]
  program: {
    overview: 'Overview',
    publish: 'Publish',
    published: 'Program published',
    publishHint: 'Publishing needs at least one day with exercises.',
    publishError: "Couldn't publish the program.",
    duplicate: 'Duplicate',
    assign: 'Assign',
    blocks: 'Blocks',
    addBlock: 'Add block',
    blockName: 'Block name',
    blockNamePlaceholder: 'Upper strength',
    blockFocus: 'Focus',
    blockWeekStart: 'First week',
    blockWeekEnd: 'Last week',
    blockNotes: 'Notes',
    blockRange: (start: number, end: number) =>
      start === end ? `Week ${start}` : `Weeks ${start}–${end}`,
    blocksEmpty: 'No blocks yet. Blocks group weeks under a name.',
    blockOverlap: 'Blocks cannot overlap. Pick a free week range.',
    blockOrderInvalid: 'The first week must be on or before the last week.',
    blockOutOfRange: (weeks: number) => `Weeks must be between 1 and ${weeks}.`,
    blockSaved: 'Block saved',
    confirmDeleteBlock: 'Delete this block? The weeks stay, they just lose the name.',
    calendar: 'Calendar',
    calendarHint: 'Each cell is one day. Open a week to edit it.',
    openWeek: 'Open week',
    restDay: 'Rest',
    emptyDay: 'Empty',
    exerciseCount: (n: number) => (n === 1 ? '1 exercise' : `${n} exercises`),
    notFound: 'This program does not exist or was deleted.',
  },

  // ------------------------------------------- /training/programs/[id]/weeks/[w]
  week: {
    title: (week: number) => `Week ${week}`,
    previousWeek: 'Previous week',
    nextWeek: 'Next week',
    editDay: 'Edit day',
    duplicateWeek: 'Duplicate week',
    duplicateTitle: (week: number) => `Copy week ${week} to…`,
    targetWeeks: 'Target weeks',
    keepLoads: 'Keep prescribed loads',
    keepLoadsHint: 'Off: the copy keeps sets and reps but clears the weights.',
    duplicateAction: 'Copy week',
    duplicated: 'Week copied',
    duplicateError: "Couldn't copy the week.",
    noTargets: 'Pick at least one target week.',
    dayNames: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    dayNamesLong: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    loadError: "Couldn't load this week.",
  },

  // -------------------------------------------- /training/programs/[id]/days/[n]
  dayEditor: {
    title: 'Day editor',
    dayName: 'Day name',
    dayNamePlaceholder: 'Upper B',
    focus: 'Focus',
    focusPlaceholder: 'Push',
    notes: 'Notes',
    restDay: 'Rest day',
    restDayHint: 'A rest day has no exercises. Clients see it as rest.',
    addExercise: '+ Add exercise',
    removeExercise: 'Remove',
    moveUp: 'Move up',
    moveDown: 'Move down',
    sets: 'Sets',
    reps: 'Reps',
    repsPlaceholder: '5, 8-10 or AMRAP',
    rpe: 'RPE',
    rest: 'Rest',
    load: 'Load',
    loadWeight: 'Weight',
    loadPercent: '% of 1RM',
    loadRpe: 'RPE',
    loadBodyweight: 'Bodyweight',
    supersetGroup: 'Superset',
    supersetPlaceholder: 'A',
    exerciseNotes: 'Note',
    exerciseNotesPlaceholder: 'Strict press.',
    setOverrides: 'Per-set overrides',
    setOverridesHint: 'Leave a field empty to use the prescription above.',
    addOverride: 'Add set override',
    removeOverride: 'Remove override',
    setNumber: 'Set',
    duplicateDay: 'Duplicate this day to…',
    duplicateTitle: 'Copy this day to…',
    targetDays: 'Target days',
    duplicateAction: 'Copy day',
    duplicated: 'Day copied',
    saved: 'Day saved',
    saveError: "Couldn't save. Your changes are still here.",
    discardTitle: 'Discard changes?',
    discardConfirm: 'Discard changes? Your edits will be lost.',
    discard: 'Discard',
    keepEditing: 'Keep editing',
    unsaved: 'Unsaved changes',
    empty: 'No exercises yet.',
    emptyAction: 'Add the first exercise',
    setsRange: 'Sets must be between 1 and 20.',
    repsRequired: 'Reps are required.',
    loadValueRequired: 'Enter a load value or switch the load mode.',
  },

  // -------------------------------------------------------- exercise picker
  picker: {
    title: 'Add exercise',
    search: 'Search exercises',
    allMuscles: 'All muscles',
    recentlyUsed: 'Recently used',
    recentlyUsedWith: (name: string) => `Recently used with ${name}`,
    catalog: 'Catalog',
    empty: 'No exercises match this search.',
    loadError: "Couldn't load the exercise catalog.",
    add: 'Add',
  },

  // ------------------------------------------------- /training/exercises
  exercises: {
    title: 'Exercises',
    subtitle: 'The global catalog is read-only. Custom exercises belong to this workspace.',
    globalTab: 'Global catalog',
    customTab: 'Custom',
    newExercise: 'New exercise',
    editExercise: 'Edit exercise',
    name: 'Name',
    namePlaceholder: 'Landmine press',
    category: 'Category',
    categoryStrength: 'Strength',
    categoryCardio: 'Cardio',
    categoryMobility: 'Mobility',
    categoryOther: 'Other',
    primaryMuscles: 'Primary muscles',
    primaryMusclesPlaceholder: 'chest, shoulders',
    equipment: 'Equipment',
    equipmentPlaceholder: 'Barbell',
    isUnilateral: 'Unilateral',
    defaultRest: 'Default rest',
    instructions: 'Instructions',
    instructionsPlaceholder: 'Two lines on how to do it well.',
    readOnly: 'Read-only',
    globalEmpty: 'The global catalog is empty.',
    customEmpty: 'No custom exercises yet.',
    customEmptyAction: 'Create the first one',
    created: 'Exercise created',
    updated: 'Exercise updated',
    deleted: 'Exercise deleted',
    confirmDelete: 'Delete this exercise? Programs that use it keep the name.',
    saveError: "Couldn't save the exercise.",
    nameRequired: 'Name is required.',
  },

  // ------------------------------------------------- client training panel
  panel: {
    title: 'Training',
    activeProgram: 'Active program',
    adherence: 'Adherence',
    adherenceLabel: (pct: number) => `Adherence ${pct}%`,
    missedInBlock: (n: number) =>
      n === 1 ? '1 session missed this block' : `${n} sessions missed this block`,
    weekOf: (current: number, total: number) => `Week ${current} of ${total}`,
    currentWeek: 'This week',
    recentLogs: 'Recent logs',
    records: 'Records',
    strength: 'Strength',
    estimated1rm: 'est. 1RM',
    selectExercise: 'Exercise',
    assignProgram: 'Assign program',
    openProgram: 'Open program',
    noProgram: (name: string) => `${name} has no program yet.`,
    noProgramGeneric: 'This client has no program yet.',
    noLogs: 'Nothing logged yet.',
    noRecords: 'Records show up here after the first heavy set.',
    noTrend: 'Log two sessions to see the trend.',
    loadError: "Couldn't load this client's training.",
    // review
    review: 'Review',
    reviewed: 'Reviewed',
    writeComment: 'Write a comment',
    commentPlaceholder: 'Bar speed held on the last two sets.',
    send: 'Send',
    congratulate: 'Congratulate',
    congratulated: 'Congratulated',
    sentTo: (name: string) => `Sent to ${name}`,
    reviewError: "Couldn't send. Try again.",
    // log summary
    duration: 'Duration',
    sets: 'sets',
    volume: 'volume',
    prCount: (n: number) => (n === 1 ? '1 record' : `${n} records`),
    partial: 'Partial session',
    clientNote: 'Client note',
    // records table
    exercise: 'Exercise',
    best1rm: 'Best est. 1RM',
    bestWeight: 'Best weight',
    bestReps: 'Best reps',
    achieved: 'Achieved',
  },

  // ------------------------------------------------------------- assignment
  assign: {
    title: 'Assign program',
    program: 'Program',
    clients: 'Clients',
    start: 'Start',
    startThisWeek: 'This week',
    startNextMonday: 'Next Monday',
    startHint: 'Programs start on a Monday. Days before today show as rest.',
    mode: 'Mode',
    modeCopy: 'Copy',
    modeCopyHint: 'A private copy per client. Adjust loads without touching the original.',
    modeShared: 'Shared',
    modeSharedHint: 'Everyone reads the same program. Needed for group visibility.',
    replace: 'Replace the current program',
    replaceHint: 'A client can only follow one program at a time.',
    action: 'Assign',
    assigned: 'Program assigned',
    error: "Couldn't assign the program.",
    noClients: 'Pick at least one client.',
    noProgramSelected: 'Pick a program.',
    activeAssignmentConflict: 'This client already follows a program. Turn on replace to switch.',
    endAssignment: 'End assignment',
    confirmEnd: 'End this assignment? The client keeps their logs.',
    ended: 'Assignment ended',
  },

  // ------------------------------------------------------------------ units
  units: {
    kg: 'kg',
    lb: 'lb',
    unitLabel: 'Unit',
    unitHint: 'You type in this unit. Loads are stored in kilograms.',
  },
} as const

export type TrainingStrings = typeof trainingStrings
